general:
  cmor_version: CMIP6
  CMIP_Tables_Dir: /work/ab0995/a270243/pymor_workshop/cmip6-cmor-tables/Tables/
  CV_Dir: /work/ab0995/a270243/pymor_workshop/cmip6-cmor-tables/CMIP6_CVs/

pymor:
  warn_on_no_rule: False

rules:
  - name: CO2f_Regrid
    model_variable: CO2f
    cmor_variable: fgco2
    pipelines: [my-regridder]
    inputs:
       - path: /work/ab0995/a270243/pymor_workshop/data/
         pattern: CO2f_fesom_mon_300.0101.nc
    output_directory: "."
    # Metadata block
    experiment_id: "piControl"
    grid_label: "gn"
    model_component: "oce"
    source_id: "AWI-CM-1-1-HR"
    variant_label: "r1i1p1f1"
    mesh_path: /work/ab0246/a270077/SciComp/Projects/pymor-workshop/fesom-meshes/core/

pipelines:
  - name: my-regridder
    steps:
      - pymor.core.gather_inputs.load_mfdataset
      - pymor.std_lib.generic.get_variable
      - pymor.fesom_1p4.nodes_to_levels.nodes_to_levels
      # - pymor.fesom_2p1.regridding.regrid_to_regular
      - pymor.core.caching.manual_checkpoint
      - pymor.std_lib.generic.trigger_compute
      - pymor.std_lib.generic.show_data
      - pymor.std_lib.files.save_dataset
